version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bookdb
    restart: always
    environment:
      POSTGRES_USER: efe
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U efe -d bookdb"]
      interval: 2s
      retries: 10

  app:
    build: .
    container_name: book-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: ["./wait-for-db.sh", "./main"]

volumes:
  db_data:
